# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51b975dcdf4cc4aea8f0aed4a49b76b078ad63812b4909c18f652bc0af551034e401787bbec68fb758f391a4a65d5bf44b89ee9b3791526792696d671d6725d6

test:
  secret_key_base: 89c037333595b57173a4abc75a3793b5730d9cc362288a02c20c7a24cbc262e64f0ce2aa334d95e644456bbddcbf7ad4bc1f7ca9c694cf48d5118ec404fa47e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
